### ISSUE TITLE
Episode RunTime can be null

### ISSUE THREAD

**Issue by StephenDMorris** [HristoKolev/TvDbSharper#27]
It turns out that runtime can be null as well in the Episode base and extended dto. 

![image](https://user-images.githubusercontent.com/28726011/145709154-afa2791b-ca16-4614-9e7c-58cad6f7722a.png)

**Comment by HristoKolev** [comment]
I'll take care of it.

Btw, the reason that I don't catch these thing is that the swagger that they've provided is wrong. I've had to make so many overrides to match what's actually provided, including many, many nullable fields.

The only way to know if a field is nullable is to get a response that has it as null.

Basically, thank you for reporting these things to me, otherwise I won't know to fix them. :)

**Comment by StephenDMorris** [comment]
I'm just very thankful and grateful that you are willing to fix these issues. Having your nuget package is so incredibly helpful.

**Comment by HristoKolev** [comment]
The v4.0.4 package should be available anytime now.
